### ISSUE TITLE
中国大陆无法访问

### ISSUE THREAD

**Issue by Xianwei-Zhou** [zhaochuninhefei/playWithChatGPT#1]
请问你是在什么环境下运行的，我在中国大陆开了vpn全局，使用pycharm运行时报错，在create里加上了proxies后也报错，可能是什么原因，谢谢：
Traceback (most recent call last):
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\connection.py", line 504, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\86159\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\86159\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\86159\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1124)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/86159/PycharmProjects/gptapitest/main.py", line 62, in <module>
    askAndAnwser()
  File "C:/Users/86159/PycharmProjects/gptapitest/main.py", line 45, in askAndAnwser
    response = openai.ChatCompletion.create(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "C:\Users\86159\PycharmProjects\gptapitest\lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))

**Comment by zhaochuninhefei** [comment]
看堆栈最后一句：openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))
你的全局VPN设置有问题吧，ssl连接错误了。还是得检查自己的全局VPN设置吧。

**Comment by Xianwei-Zhou** [comment]
是代理的问题，我在代码中加了os.environ["http_proxy"] = proxy
os.environ["https_proxy"] = proxy 问题解决，谢谢
